# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.2"
manifest_format = "2.0"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.Graph]]
deps = ["LinkedList", "Test"]
git-tree-sha1 = "e888578121896debb45d56b4c46b23d72599c1da"
repo-rev = "master"
repo-url = "https://github.com/nesteiner/Graph.jl"
uuid = "02309348-74b9-4183-9256-84e19e720cf7"
version = "0.1.0"

[[deps.Heap]]
deps = ["Test"]
git-tree-sha1 = "016d89115965d3a492653f78a2a66abb1370af3b"
repo-rev = "master"
repo-url = "https://github.com/nesteiner/Heap.jl.git"
uuid = "98d27c62-3826-4236-8e4a-9c35fe941180"
version = "0.1.0"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[deps.LinkedList]]
deps = ["Test"]
git-tree-sha1 = "9331f206f3561e9afe370d17e2a1c66a75d5549c"
repo-rev = "master"
repo-url = "https://github.com/nesteiner/LinkedList.jl.git"
uuid = "8bb5f1f9-8766-4891-94ae-ce2d9eef0394"
version = "0.2.0"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
